@echo off
echo 🚀 Starting AstharHat Dev Server...
echo 🛡️ Fixing PowerShell Execution Policy...
powershell -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force"
echo 📦 Installing dependencies (if needed)...
node -v
echo ⚡ Running Next.js...
node node_modules\next\dist\bin\next dev
pause
